### ISSUE TITLE
consuming streaming response will block until SSE stream ends

### ISSUE THREAD

**Issue by hitsmaxft** [avastmick/google-generative-ai-rs#19]
**Describe the bug**

stream iter response will block until SSE stream ends

**To Reproduce**
```rust

use futures::stream::{self, StreamExt};


    let response = client.post(30, &txt_request).await?;

        if let Some(gemini) = response.streamed() {
            stream::iter(&gemini.streamed_candidates)
                .for_each(|r| async {
                    output_response(r).await;
                })
            .await;
        }

```
**Expected behavior**
output_response  one by one

**Screenshots**

**Version:**
 - Version [e.g. 0.1.5]

**Additional context**

**Comment by avastmick** [comment]
I agree the current implementation is not great. It suits my needs though ;). I'll look into a 'third' path to release the returns as they come rather than 'packing' into a struct list - basically opening up the client for each response. See note that it will still be blocked to some degree due to the design decisions made by Google.

Not sure of your use case, but the Gemini API doesn't really stream the output - i.e. it does not give the output token by token / character by token, but gives it out in 'chunks', including harm and other data. It is a strange design decision by Google IMO, but I get the control over the harm and exit conditions, rather than hiding it all as OpenAI does and saying the request failed...

**Comment by avastmick** [comment]
@hitsmaxft As per our conversations in #20 and #21 we've moved this to a branch, [streamed_response](https://github.com/avastmick/google-generative-ai-rs/tree/streamed_response), for more comprehensive testing. I'm a bit time poor right now. But to summarise, there are two endpoints, the Public and that of the Vertex AI API service. I just want to make sure that all the use cases are covered as there are some subtle differences between each (which is so Google). I use this code in production... 😟 

I wrote the original client code the day after the API was released. I notice that they have updated a few things last week, so hopefully the two endpoints are now the same. I need to test and also fix #12 (which should easy). I really need some CI tests to run too 😉 

Holding this here for records.

**Comment by hitsmaxft** [comment]
current patch use blocking io in async stream , which is not a good idea.  Need one step forward to replace them with tokio.io.stdout

**Comment by avastmick** [comment]
@hitsmaxft found some time today as I needed to implement the `countTokens` handling.

I've merged your code into `main` as well as the `countTokens` functionality. Your changes broke the usage of Vertex AI endpoint, but it was an easy fix. 

I bumped the version to `0.2.1` to show that it was breaking changes, as well as addition functionality.

Thanks for your help.
